import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, Bell, CheckCircle2, CircleAlert, Clock3, Wifi, WifiOff, Volume2, VolumeX } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Card, Empty, ErrorBox, LoadingSpinner, RiskBadge } from '../components/UI.jsx';
import { useToast } from '../components/Toast.jsx';
import useLiveMonitor from '../hooks/useLiveMonitor.js';
import { fmtDur, fmtTime, label } from '../utils/format.js';

const eventNames = ['TAB_SWITCH', 'FULLSCREEN_EXIT', 'NO_FACE_DETECTED', 'MULTIPLE_FACES_DETECTED', 'LOOKING_AWAY', 'HEAD_TURN_LEFT', 'HEAD_TURN_RIGHT', 'LOOKING_DOWN', 'PHONE_DETECTED', 'CAMERA_DISABLED', 'MULTIPLE_SESSION'];
const riskClass = level => level === 'Multiple Incidents' ? 'text-red-700 bg-red-50' : level === 'Review Recommended' ? 'text-amber-700 bg-amber-50' : 'text-emerald-700 bg-emerald-50';
const countLabels = [['TAB_SWITCH', 'Tabs'], ['FULLSCREEN_EXIT', 'Fullscreen'], ['NO_FACE_DETECTED', 'No face'], ['MULTIPLE_FACES_DETECTED', 'Multiple faces'], ['LOOKING_AWAY', 'Looking away'], ['PHONE_DETECTED', 'Phone']];

export default function AdminLive() {
  const { students, events, connected, loading, error, stats } = useLiveMonitor(); const toast = useToast();
  const [exam, setExam] = useState('all'); const [search, setSearch] = useState(''); const [sound, setSound] = useState(false); const [cleared, setCleared] = useState(() => new Set()); const [newEventId, setNewEventId] = useState(''); const seen = useRef('');
  const feed = events.filter(event => !cleared.has(event._id));
  useEffect(() => { const latest = events[0]; if (!latest || latest._id === seen.current) return; seen.current = latest._id; setNewEventId(latest._id); const timer = setTimeout(() => setNewEventId(''), 1800); setCleared(current => { const next = new Set(current); next.delete(latest._id); return next; }); if (latest.severity >= 4) toast(`${label(latest.eventType)} detected for ${latest.studentName || 'a student'}`, 'warn'); if (sound) { const c = new AudioContext(); const o = c.createOscillator(); const g = c.createGain(); o.frequency.value = 720; g.gain.value = 0.04; o.connect(g); g.connect(c.destination); o.start(); o.stop(c.currentTime + 0.12); } return () => clearTimeout(timer); }, [events, sound, toast]);
  const exams = useMemo(() => [...new Set(students.map(x => x.examTitle).filter(Boolean))], [students]);
  const visible = useMemo(() => students.filter(x => (exam === 'all' || x.examTitle === exam) && (x.studentName || '').toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.riskScore - a.riskScore), [students, exam, search]);
  const [now, setNow] = useState(Date.now()); useEffect(() => { const t = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(t); }, []);
  if (loading) return <LoadingSpinner />; if (error && !students.length) return <ErrorBox text={error} />;
  return <div className="page-enter space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold uppercase tracking-widest text-blue-600">Operations center</p><h1 className="text-2xl font-bold tracking-tight text-slate-900">Live Monitor</h1><p className="text-sm text-slate-500">Anti-cheat signals and suspicious events for active exams.</p></div><button onClick={() => setSound(x => !x)} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">{sound ? <Volume2 size={16} /> : <VolumeX size={16} />} Sound alerts {sound ? 'on' : 'off'}</button></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Stat icon={Activity} label="Students live now" value={stats.total} /><Stat icon={Wifi} label="Online" value={stats.online} /><Stat icon={WifiOff} label="Offline" value={stats.offline} /><Stat icon={CircleAlert} label="Flagged" value={stats.flagged} /><Stat icon={connected ? CheckCircle2 : WifiOff} label="Socket" value={connected ? 'Connected' : 'Disconnected'} /></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]">
      <Card><div className="mb-4 flex flex-wrap gap-2"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search student..." className="min-w-[200px] flex-1 rounded-xl border border-slate-200 px-3 py-2 text-sm text-slate-800 outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-100" /><select value={exam} onChange={e => setExam(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2 text-sm text-slate-700 outline-none focus:border-blue-500"><option value="all">All exams</option>{exams.map(x => <option key={x}>{x}</option>)}</select></div>
        {visible.length ? <div className="space-y-3">{visible.map(student => <LiveStudent key={student._id} student={student} now={now} />)}</div> : <Empty text="No students are taking exams right now" />}</Card>
      <Card className="max-h-[680px] overflow-auto"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">Live event feed</h2><button onClick={() => setCleared(new Set(events.map(event => event._id)))} className="text-xs text-slate-500 hover:text-red-600">Clear feed</button></div>{feed.length ? <div className="space-y-3">{feed.map(e => <div key={e._id} className={`rounded-lg border-l-4 border-amber-400 bg-amber-50/60 p-3 text-xs ${newEventId === e._id ? 'animate-pulse ring-2 ring-amber-300' : ''}`}><div className="flex justify-between text-slate-500"><span>{fmtTime(e.timestamp)}</span><span>severity {e.severity}</span></div><p className="mt-1 font-semibold text-slate-800">{label(e.eventType)}</p><p className="text-slate-600">{e.studentName || 'Student'} · {e.examTitle || 'Exam'}</p></div>)}</div> : <Empty text="No incoming signals" />}</Card>
    </div>
  </div>;
}
function Stat({ icon: Icon, label: text, value }) { return <Card className="p-4"><div className="flex items-center justify-between"><div><p className="text-xs text-slate-500">{text}</p><p className="mt-1 text-xl font-bold text-slate-900">{value}</p></div><span className="rounded-xl bg-blue-50 p-2 text-blue-600"><Icon size={19} /></span></div></Card>; }
function LiveStudent({ student, now }) { const remaining = Math.max(0, Math.ceil((new Date(student.endTime).getTime() - now) / 1000)); return <div className="rounded-xl border border-slate-200 bg-white p-4 transition hover:border-blue-200 hover:shadow-sm"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold text-slate-900">{student.studentName || 'Student'}</h3><p className="text-xs text-slate-500">{student.examTitle || 'Exam'}</p></div><RiskBadge level={student.riskLevel} /></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-600 sm:grid-cols-4"><span className="flex items-center gap-1"><Clock3 size={13} />{fmtDur(remaining)}</span><span className={student.online ? 'text-emerald-600' : 'text-slate-400'}>{student.online ? '● Online' : '○ Offline'}</span><span>Progress {student.answeredCount}/{student.totalQuestions}</span><span>Risk score {student.riskScore}</span></div><div className="mt-3 flex flex-wrap gap-1">{countLabels.map(([key, text]) => <span key={key} className="rounded bg-slate-100 px-2 py-1 text-[10px] text-slate-600">{text}: {student.counts?.[key] || 0}</span>)}</div><Link to={`/admin/attempts/${student._id}`} className="mt-3 inline-block text-xs font-semibold text-blue-600 hover:text-blue-800">View report →</Link></div>; }
