import { useEffect, useState } from 'react'; import { Link } from 'react-router-dom'; import { Users, FileText, ClipboardList, Percent, ArrowRight, ShieldCheck, Activity } from 'lucide-react';
import api, { errMsg } from '../services/api.js'; import { Card, Stat, Table, LoadingSpinner, ErrorBox, Empty } from '../components/UI.jsx'; import { fmtDate, label } from '../utils/format.js';
export default function AdminDashboard() {
  const [s, setS] = useState(null); const [inc, setInc] = useState([]); const [err, setErr] = useState('');
  useEffect(() => { Promise.all([api.get('/admin/stats'), api.get('/anti-cheat/recent')]).then(([a, b]) => { setS(a.data); setInc(b.data); }).catch(e => setErr(errMsg(e))); }, []);
  if (err) return <ErrorBox text={err} />; if (!s) return <LoadingSpinner />;
  return <div className="page-enter space-y-6">
    <section className="relative overflow-hidden rounded-3xl bg-[#123b2a] p-6 text-white shadow-xl shadow-slate-200 md:p-8"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-blue-600/20 blur-2xl" /><div className="relative flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-blue-300">Admin workspace</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Dashboard overview</h1><p className="mt-2 max-w-xl text-sm leading-6 text-slate-300">Monitor platform activity, review assessment performance, and keep every exam running smoothly.</p></div><div className="flex items-center gap-2 rounded-xl border border-emerald-400/20 bg-emerald-400/10 px-3 py-2 text-xs font-medium text-emerald-300"><Activity size={15} /> System operational</div></div></section>
    <div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><Stat label="Students" value={s.totalStudents} icon={Users} /><Stat label="Exams" value={s.totalExams} icon={FileText} /><Stat label="Attempts" value={s.totalAttempts} icon={ClipboardList} /><Stat label="Average score" value={s.averageScore + '%'} icon={Percent} /></div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(280px,360px)]">
      <Card><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="font-semibold text-slate-900">Recent attempts</h2><p className="mt-1 text-xs text-slate-500">Latest student assessment activity</p></div><Link className="inline-flex items-center gap-1 text-xs font-semibold text-blue-600 hover:text-blue-800" to="/admin/attempts">View all <ArrowRight size={14} /></Link></div>{s.recentAttempts.length ? <Table head={['Student', 'Exam', 'Score', 'Status', '']}>{s.recentAttempts.map(a => <tr key={a._id}><td className="py-3 font-medium text-slate-800">{a.studentId?.name}</td><td className="text-slate-600">{a.examId?.title}</td><td className="font-semibold text-slate-800">{a.score}/{a.examId?.totalMarks}</td><td><span className="rounded-full bg-slate-100 px-2 py-1 text-xs capitalize text-slate-600">{a.status.replace('_', ' ')}</span></td><td><Link className="font-semibold text-blue-600 hover:text-blue-800" to={`/admin/attempts/${a._id}`}>Report</Link></td></tr>)}</Table> : <Empty text="No attempts yet" />}</Card>
      <Card><div className="mb-4 flex items-center gap-3"><span className="rounded-xl bg-amber-50 p-2.5 text-amber-600"><ShieldCheck size={20} /></span><div><h2 className="font-semibold text-slate-900">Anti-cheat signals</h2><p className="mt-1 text-xs text-slate-500">Recent events requiring review</p></div></div>{inc.length ? <div className="space-y-3">{inc.slice(0, 5).map(e => <div key={e._id} className="rounded-xl border border-slate-100 bg-slate-50 p-3"><div className="flex items-center justify-between gap-2"><p className="text-sm font-semibold text-slate-800">{label(e.eventType)}</p><span className="text-[11px] text-slate-400">{fmtDate(e.timestamp)}</span></div><p className="mt-1 text-xs text-slate-500">{e.studentId?.name || 'Student'} · {e.examId?.title || 'Exam'}</p></div>)}</div> : <Empty text="No signals recorded" />}</Card>
    </div>
  </div>;
}
