import { useEffect, useState } from 'react'; import { useNavigate } from 'react-router-dom'; import { BookOpen, CheckCircle2, Clock3, Sparkles, Trophy, ArrowRight } from 'lucide-react';
import api, { errMsg } from '../services/api.js'; import { useAuth } from '../context/AuthContext.jsx'; import ExamCard from '../components/ExamCard.jsx';
import { LoadingSpinner, ErrorBox, Card } from '../components/UI.jsx';
export default function StudentDashboard() {
  const { user } = useAuth(); const nav = useNavigate(); const [exams, setExams] = useState(null); const [attempts, setAttempts] = useState([]); const [err, setErr] = useState('');
  useEffect(() => { Promise.all([api.get('/exams'), api.get('/attempts/mine')]).then(([e, a]) => { setExams(e.data); setAttempts(a.data); }).catch(e => setErr(errMsg(e))); }, []);
  if (err) return <ErrorBox text={err} />; if (!exams) return <LoadingSpinner />;
  const done = attempts.filter(a => a.status !== 'in_progress');
  const completedCount = done.length;
  return <div className="page-enter space-y-8">
    <section className="relative overflow-hidden rounded-3xl bg-[#123b2a] px-6 py-8 text-white shadow-xl shadow-slate-200 sm:px-10 sm:py-10"><div className="absolute -right-12 -top-20 h-64 w-64 rounded-full bg-blue-600/20 blur-2xl" /><div className="absolute bottom-0 right-1/3 h-32 w-32 rounded-full bg-indigo-500/10 blur-xl" /><div className="relative max-w-2xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-blue-400/20 bg-blue-500/10 px-3 py-1.5 text-xs font-semibold text-blue-200"><Sparkles size={14} /> Your learning dashboard</div><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Welcome back, {user.name}!</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-300">Keep building your momentum. Continue an exam, explore upcoming assessments, and review your latest results.</p><div className="mt-6 flex flex-wrap gap-3 text-xs"><span className="flex items-center gap-2 rounded-lg bg-white/10 px-3 py-2"><BookOpen size={15} /> {exams.length} total exams</span><span className="flex items-center gap-2 rounded-lg bg-white/10 px-3 py-2"><CheckCircle2 size={15} /> {completedCount} completed</span></div></div></section>
    <section className="grid gap-4 sm:grid-cols-3"><Card className="flex items-center gap-4 transition hover:-translate-y-0.5"><span className="rounded-xl bg-blue-50 p-3 text-blue-600"><BookOpen size={20} /></span><div><p className="text-xs text-slate-500">Total exams</p><p className="text-2xl font-bold text-slate-900">{exams.length}</p></div></Card><Card className="flex items-center gap-4 transition hover:-translate-y-0.5"><span className="rounded-xl bg-amber-50 p-3 text-amber-600"><Clock3 size={20} /></span><div><p className="text-xs text-slate-500">In progress</p><p className="text-2xl font-bold text-slate-900">{exams.filter(e => e.attempt?.status === 'in_progress').length}</p></div></Card><Card className="flex items-center gap-4 transition hover:-translate-y-0.5"><span className="rounded-xl bg-emerald-50 p-3 text-emerald-600"><Trophy size={20} /></span><div><p className="text-xs text-slate-500">Completed</p><p className="text-2xl font-bold text-slate-900">{completedCount}</p></div></Card></section>
    <section className="grid gap-5 sm:grid-cols-2"><button onClick={() => nav('/student/exams')} className="group surface p-6 text-left transition hover:-translate-y-1 hover:shadow-lg"><span className="mb-4 inline-flex rounded-xl bg-blue-50 p-3 text-blue-600"><BookOpen size={22} /></span><h2 className="text-lg font-bold text-slate-900">My exams</h2><p className="mt-1 text-sm text-slate-500">View available, upcoming, and completed exams.</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-blue-600">Open exams <ArrowRight size={15} className="transition group-hover:translate-x-1" /></span></button><button onClick={() => nav('/student/results')} className="group surface p-6 text-left transition hover:-translate-y-1 hover:shadow-lg"><span className="mb-4 inline-flex rounded-xl bg-emerald-50 p-3 text-emerald-600"><Trophy size={22} /></span><h2 className="text-lg font-bold text-slate-900">Results</h2><p className="mt-1 text-sm text-slate-500">Review your scores and submitted assessments.</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-blue-600">Open results <ArrowRight size={15} className="transition group-hover:translate-x-1" /></span></button></section></div>;
}
